### PR TITLE
fix problems with finishing a measurement line on a marker icon

### PR DESCRIPTION
**Pull request by yrral86**
I was getting errors when trying to end a line on a marker icon.  To resolve this, I made the following changes:
1. I removed the click handler for the last CircleMarker as a means of triggering _finishPath and instead am using the leaflet dblclick event to trigger it.
2.  I made _polylineArc not generate NaNs if the to and from coordinates are identical. (it shouldn't happen now, but that was the first problem I saw as I was tracing this down)

### CODE REVIEW

**Comment by yrral86** [comment]
You'll probably want to hold off on this... I found a bug with changing units.  If you change units and then draw a new line, the last tooltip on the new line causes an error when changing units.  I should be able to track it down tomorrow, but if you happen to spot the issue, please let me know.

**Comment by yrral86** [comment]
It should be ready to go if you want it.  I ended up doing a fairly major cleanup of the state handling so I'll understand if you want to reject this PR.  There is now a single object for managing the state during drawing (created by `_startLine` and stored as `_currentLine`).  Once the measurement is completed, the `_currentLine` object is added to an array called `self._lines`.  This eliminates the 4 variables for managing completed measurement state, as well as the 8 variables for managing an in progress measurement, which IMO makes things a bit cleaner.  I'm willing to do a bit of cleanup if you have any feedback.

**Comment by ppete2** [comment]
Hi, thanks very much for your work! 
I'll look at it this weekend. Just for debugging: What exactly did you do to get the errors on JS-console you talked in your 1st post?

1. Do you mean on of the circles of the measurement line? Or some external Leaflet Marker? If clicking onto a line's marker I'm not getting an error and the line is being finished with a double-click.

2. I can not reproduce this error, since i'm not able to get exactly same coords of start and finish point of a line, even if finish point looks like his over start point.

**Comment by yrral86** [comment]
For both cases the issue was a leaflet marker outside of the plugin.  The marker had and image based icon, but I don't know if that makes a difference.

**Comment by ppete2** [comment]
I see! So you drawed a standard-leaflet marker and tried to measure a path starting and ending at this marker?

**Comment by yrral86** [comment]
I had several markers and starting a measurement on a marker was fine.
Clicking on markers for intermediate points was fine too. Ending on any non
measurement marker caused a stack trace and the measurement got into a bad
state.  If I recall correctly, the temp line persisted in following the
mouse and clicks were ignored or caused further errors.  We are also going
to using the prunecluster plugin so if you can't reproduce with normal
markers that might be necessary to trigger it.  The markers were not
clustered when I saw the problem.

**Comment by ppete2** [comment]
@yrral86 I just noticed if using the Demos within Mobile Browsers (Chrome, Firefox e.g.) the measuring lables are missing and each point gets some strange "shadow" point below too.
Do you have an idea how to fix this for the Mobile Browsers?

**Comment by yrral86** [comment]
By inspecting the DOM inside leaflet-marker-pane, I saw that the "shadow" points are the tooltips, but the width and height are being set to 0 on mobile.  Unfortunately, I haven't done much with mobile leaflet.

**Comment by ppete2** [comment]
Hi @yrral86 
I made the plugin work within Mobile Browsers again. But theirs still a tiny problem which has been introduced with your PR: 
The last point needs to be finishable with just **one** mousclick/tap too, not just with doubleclick. Why?

**_a)_** if the the users of either Desktop or Mobile browsers are not sure if a point would be the finishing point: therefor make just a **single** click, move around the mouse, then suddenly are sure that the former point should be the finishing point and therefor **doubleclick** (or singleclick) onto the last point. problem: a new, tiny line segment including a new arrow and a new tooltip is created by mistake.

**_b)_** there's a problem that some Mobile Browsers (like Mobile Chrome) don't unterstand some kind of events yet (doubletaps, touchmove). at least they understand **singleclick**. So people using Mobile Chrome are dependent that singlclick on last point to finish a line works.

Are you able to finish a line with a **single click** onto last point work again? Would be great, thank you!

**Comment by yrral86** [comment]
@ppete2 
Sorry for the delayed response.  My wife just gave birth.  I will get to this as soon as I can, but I've got a lot to catch up on.

If you have the time to try it before I get to it, I would guess you could get the behavior you want by replacing the return in this code from ~ line 681
` if (lastPoint && lastPoint.equals(latlng)) {
                    	return;
}`
with a call to self._finishPath.  That should make it work for both clicking the last point and double clicking at the end.  I'm unsure if you'll still need the `dblclick` listener registered/unregistered in _toggleMeasure, but you may be able to remove it.

**Comment by yrral86** [comment]
https://github.com/ppete2/Leaflet.PolylineMeasure/pull/17

**Pull request merged**
