### PR TITLE
Update Leaflet.PolylineMeasure.js

### PR DESCRIPTION
**Pull request by iofirag**
add missing variables declarations

### CODE REVIEW

**Comment by ppete2** [comment]
Hello @iofirag !

I looked at your PR. I noticed that you changed quite a lot _"this."_ into _"self."_
I'm sceptic about these modifications, because exactly those this vs. self behaviuor was improved on Feb.9th by @yrral86 to make it possible to use the plugin at once on 2 maps.

So why do you think it's better to change all these variables again?

**Comment by yrral86** [comment]
A global `self` variable breaks the plugin when used in multiple maps.   Using `this` makes sure we are using the correct instance of the plugin.  You are also removing some recently added configuration options. 
 It is also entirely unclear to me what changes you are trying to make here.  I suggest you rebase your changes on the current master branch and provide a description of what you are changing and why.

**Comment by ppete2** [comment]
Closing pull Request.

**Comment by iofirag** [comment]
i understand, my motivation to do that, was because i'm using stenciljs and add your plugin, but then it gave me an errors when i try to use it for measuring.
the errors related to variables that was not defined.

> Uncaught ReferenceError: tooltipStart is not defined
> Uncaught TypeError: self._currentLine.points.last is not a function

so i start to add `var` before the issued variables that the console tell me about them.

**Pull request closed without merging**
